import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// Mantine UI
import '@mantine/core/styles.css';
import { MantineProvider } from "@mantine/core";
import '@mantine/charts/styles.css';
import '@mantine/notifications/styles.css';

// Styled
import StyledComponentsRegistry from "../../lib/styled-components/registry";
import { GlobalStyle } from "@/styles/global/global";
import ThemeProvider from "@/providers/ThemeProvider";
import NextAuthSessionProvider from "@/providers/NextAuthSessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dash.go",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NextAuthSessionProvider>
          <StyledComponentsRegistry>
            <MantineProvider>
              <ThemeProvider>
                {children}
                <GlobalStyle />
              </ThemeProvider>
            </MantineProvider>
          </StyledComponentsRegistry>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}